name: Hello World

on:
    push:
        branches:
            [main]
jobs:
    hello:
        runs-on: ubuntu-22.04
        steps:
            - name: Hello World
              run: echo "Hello, World!"

            - name: Ver fechas del runner
              run: date

    repo-files:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: List repository files
              run: ls -la
